### ISSUE TITLE
Trigger ID, parameter ID

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor-Issues#14]
You asked me to start a new issue even if it is a little one, so that is what I do now. :)
In 1.0.5., I can't see any TRNG trigger ID number, to identify A41, F118, C15 etc.
Plus, parameter lists also need ID's, For example, "Variables" flipeffects has a list for "... memory zone fields", and I sometimes need the ID number of that field, not only the name. And it is only one example. :)

**Comment by ActuallyaDeviloper** [comment]
What would you think about a checkbox in the dialog to switch between manual number input and the menus?

**Comment by AkyV** [comment]
- First aspect: it is good, because:
1. There are often and popular triggers which are mostly known in a short form, like A41 or F118, easier to find them this way, like searching them in menus.
2. When people are talking about triggers, they often say F52, A14, C3 etc, instead of the trigger name, so  I need a code number everyway, to find them even if I don't know the name what name wasn't told by anone.

- Second aspect: it is not enough, because:
Sometimes I need the ID of something. For example, I need the inventory index of an item. It is not the slot or item index. Items in the inventory have an own item range as well. For example, as far as I know, it is 20 for big medipack.
Sometimes Paolone says in the readme files: "type here the inventory index of the required item, you can find the index list in XY trigger". So I need to open XY trigger parameter list, search for big medipack there, to identify ID20, like:

20: Big medipack.

But, if I understand well, you say there would be two possibilities:

- Either 20,
- or big medipack.

But if I choose "big medipack" then how can I know that the value I search for, is 20?

Again, it was only an example, there are more issues than an inventory index thing. For example, see that A41 example again.  i mean, I know that this popular trigger has A41 code, because in NGLE I can see both the code and the trigger name.
But if I only see the trigger name, then where is listed that "A41 is the code that belongs to this name"?

So I think these feattures are all important:
- display parameter/trigger etc. codes AND names at the same time,
- search trigger with code number,
- search trigger with name or name part.

**Comment by ActuallyaDeviloper** [comment]
Thanks for the elabore feedback.

What I have in mind was actually was about changing the _view_. If you put in something in the raw data mode and you switch, it will show the associated enumeration if there is one. And the other direction as well of course.

I may have misunderstand your concerns though.

Small related remark: You won't be able to get IDs of objects though because we do not allocate IDs for objects.

**Comment by AkyV** [comment]
Would you tell examples for both directions, please? It is not clear for me what you say...
----
About the remark: But you have it! )
I mean, if you have scripted value (and you already have it!) on the panel, then one number of it is the object index. 
I hope it helps to understand:

http://www.tombraiderforums.com/showthread.php?t=205352

**Comment by ActuallyaDeviloper** [comment]
No, we don't have the scripted value until you create it by clicking on the script box.
Unless you do that, there is really _no_ script Id for the object.

Why is this done this way? There are a couple of different reasons for this actually...
- Since we track objects by triggers by object identity, if you remove the object the trigger *will* not be in some kind of dangling state but it will by itself be deactivated as long as no new object is specified.
- And on a related note, we are able to copy complete room setups including all triggers between projects. As long as no triggers are exported, all behaviour can be perfectly copied since we don't have script id collisions.
- We don't have any kind of object limit. Since script ids are a very limited resource, if every object needed to always have a script id, we would also need to limit all kinds of objects again.

**Comment by AkyV** [comment]
See, it starts being really complicated to understand. :) Probably the best way is if you do this feature and we will test it.
However, I am a bit worried now about some TRNG features (in plugin or whatever else) that eg. converts "editor ID" into "game ID". (Because the ID of the object is different in in TRLE/NGLE and the game.) Same with things like absolute/relative animation indices conversion etc., and a few similar "code pairs".

**Comment by ActuallyaDeviloper** [comment]
I apologize for my extreme slowness, I was recently not having much time for TE.
Anyhow, I finally came around to do it. You can give it a shot here:
[TombLib.zip](https://github.com/MontyTRC89/Tomb-Editor-Issues/files/1653721/TombLib.zip)
There is now a raw mode in the trigger window. I hope people will not accidentally activate it and create broken triggers...

Do you want to elaborate on the thing about absolute/relative animation indices?

**Comment by AkyV** [comment]
Hello! This raw mode is really cool, and I can even type a number to be selected!  i like it.  :)

Please don't forget a tiny but important thing: "OldFlip" flipeffects are the TRNG versions of TRLE flipeffects, that's why they sometimes don't have a parameter list (like other TRNG triggers) but they have a box to type the trigger value (like non-TRNG triggers). The problem is Tomb Editor always wants a parameter list to TRNG triggers, even for "OldFlips", but they don't have, and we can't type a value there either. (It  is easy to find them:  where you can find "&" sign  in the trigger name, there should be a number input in "&" window, but there isn't.)

About relative/absolute indices, here is a whole chapter of all the important converversion types - it is a plugin-making materia though, it tells everything which is important:

http://www.tombraiderforums.com/showpost.php?p=7793086&postcount=24
