### ISSUE TITLE
Room map enhancements

### ISSUE THREAD

**Issue by AkyV** [MontyTRC89/Tomb-Editor-Issues#19]
- Vertical 2D map (not only vertical levels in the horizontal map, as Tomb Editor just has) - see NGLE V2dmap button and South/East/West/North button.
- A primitive "compass" that helps to understand the map. I mean, 

Tomb Editor North == Game North

Game North != NGLE North == TRLE North

Many TRNG triggers have north/east etc. in they parameters. People should know that which directions they are, being in Tomb Editor.

**Comment by ActuallyaDeviloper** [comment]
We considered adding the sideways 2D map view before but postboned/discarded the idea in favor of the depth bar.

The fact that TRNG trigger direction used the winroomedit system seems very unfortunate.
I think that maybe we should instead fix the old cardinal direction namings to avoid confusion.
Let's just show the new cardinal directions (+ name the coordinate axe while we are at it too!)

Do you know whether or not TRNG was consistent in itself at least in regards to this?

**Comment by AkyV** [comment]
Depth bar:
So is there a hope for a 2D map like that in the future? Depth bar is cool, but not spectacular enough. At least, for me. :)

Cardinal points:
A organic system is cool. However, several documents refer to TRLE/NGLE cardinal points, even out of
the TRNG root. For example, my plugin's TXT. Why? Simple. This is the order in TRNG documents, so I also applied it.
That is why I suggest at least terms like "North (TRLE/TRNG: west)" in Tomb Editor documents. I bet TREP and Dxtre3d users also got used to it. :)

So, yes, TRNG consistent with that. So eg. if Paolone says in a trigger parameter list that "north", then that is always TRLE/NGLE north, which is game east.

**Comment by MontyTRC89** [comment]
I don't know if the issue is solved, but I've just checked. In game north is equal to +Z (north) in editor so probably @ActuallyaDeviloper fixed it.

**Comment by AkyV** [comment]
Hi! The problem with cardinal points was not what TE shows. The problem IS that, again

TE North == Game North != NGLE North == TRLE North.

So, what I suggested as a development was a little compass that helps. So, eg. if I look North in TE, then I will know that it is also game North, but if I want to check the same direction in NGLE (and TRNG trigger names which are also used by TE!) or TRLE, then I will know that is East there.

Anyway, I keep my other suggestionwith the vertical 2D map. :)

**Comment by ActuallyaDeviloper** [comment]
I can't get quite behind the idea, that it would be a good idea to present multiple coordinate systems. Durding the development of TE there was a lot of confusion around coordinate systems, I am very happy that we were able to get past that and consistently use one coordiante system. 
One reason why we adoped the engine's coordinate system is that really, we can't adjust the engine, all wad tools and script file coordinates. The only possibly consistent choice (throughout our editor ecosystem) in that regard was to go with the engine's convention.

Another reason is that the winroomedit coordinate system is really just a gigantic mess. The tool was originally written by Core Design for internal purposes. The simplest way to draw something on the screen is to just use room coordinates as-is on screen. By accident this makes the X coordinate go from left to right and Y from top to bottom, it just happens to be the default in all traditional 2D drawing APIs, because CRT's worked that way back in the day.
I believe the coordinate system as displayed was therefore just an accident, afaik there were no mentions of those 'CRT-cardinal directions' in winroomedit itself (including TREP) or Dxtre3D for that matter (that seems to use the engine/'our' coordinate system when I look at it's 2D map, correct me if I am wrong)
So everything was fine except the way winroomedit displays the 2D maps. But then very unfortunately Paolone started using winroomedit's swapped coordinate system as a base, but not everwhere. Just for cardinal directions. Coordinates in TRNG still use the games coordinate system, were X coordinates correspond to the Z-axis (or Y on screen) in winroomedit.
Regarding cardinal direction, that seems to me like looking at rotated street map (winroomedit's display) from the backside and then claiming 'south' is still the top.
No, that's not how it's supposed to work. South is only at the top when you look at it the right way. South is supposed to be a property of the map's coordinate system not the viewer's coordinate system.

You mentioned that maybe other TRNG users also adopted this convention. This is very unfortunate, however I really doubt confusion will disappear, when we start referenceing more than 1 coordinate system in the editor. I can tell you this as a levelbuilder, I was never able to understand this and randomly tried every direction until one finally worked.

Regarding documents, I have updated the trigger descriptions for now that we ship, so that they use the engine's cardinal directions.
So now for example we say
`Move. Move to -X direction (west) &lt;#&gt;animating for (E) clicks`
instead of 
`Move. Move to north &lt;#&gt;animating for (E) clicks`

I realize that there are probably also some other documents affected, but we need to at least try to solve the problem at it's root.

**Comment by AkyV** [comment]
Thank you for this huge explanation. With trigger names changed, I think everything will work fine, people will get used to it.
However, I still would like to suggest a little development. It would be kind from the developers. Not a "duplicated" coordinate system, only a tiny textual thing. I mean, cardinal points mentioned (typed) next to all the four sides of the TE Editor Window, outside of it, for example, at the top of TE: "TE North/Game North/NGLE+TRNG East/TRLE East/Dxtre3D ... ".  (Honestly, I don't really know Dxtre3D.)
And it is not only about kindness. As you say, there are also other documents. I mean, for example, I have plugin triggers where I say eg. "South according to Room Editor view". This explanation will also be present in TE, if one day TE will support plugins.
This textual thing is very simple, I think, and helps a lot to understand and identify directions.

Anyway, I highly agree that one coordinate system should be pretty enough.
